### ISSUE TITLE
A native host for linux?

### ISSUE THREAD

**Issue by tazihad** [pouriap/Firefox-DownloadGrab#2]
I come from flashgot forum

**Comment by pouriap** [comment]
The native host actually consists of two parts. The main part that communicates with download managers, which is flashgot.exe and a client which is basically a bridge between the browser addon and flashgot.exe

The bridge is cross-platform because it's based on Node.js

The problem is with flashgot.exe. The thing is I never used it on Linux before so I'm not sure exactly how it works. I'm gonna have to take a deeper look to figure it out. But technically speaking if it worked before I should be able to get it to work again.

**Comment by pouriap** [comment]
Linux support is of course something I plan to do but as you can tell I got lazy and didn't add the missing features after the addon became good enough for me.

And currently I'm pretty busy with work and a side project I have. But I totally plan to finish this addon in the future.
